config/routes.rb
Playtogether::Application.routes.draw do

  resources :key_values

  namespace :admin do
    resources :users do
      member do
        get 'user_ban'
      end
    end

    resources :photoalbums do
      resources :photos
      get 'upload'
    end

    resources :photos do
      get 'upload'
    end

    resources :posting_updates do
    end

    resources :places do
      member do
        get 'spots_for_select'
        get 'children_nodes'
      end
    end

    resources :sport_types do
      member do
        get 'children_nodes'
      end
    end
  end

  get 'likes/like'
  get 'likes/unlike'
  get 'likes/plus_minus'
  get 'retweets/create'

  match  'favorites' => 'favorites#index'
  get 'favorites/favorite'
  get 'favorites/unfavorite'

  match  'invites' => 'Invites#index'
  get 'invites/accept/:invite_id', :action => 'accept', :controller => 'invites', :as => 'accept_invite'
  get 'invites/cancel/:invite_id', :action => 'cancel', :controller => 'invites', :as => 'cancel_invite'

  get 'events_subscribes/create/:event_id', :action => 'create', :controller => 'events_subscribes', :as => 'subscribe_event'
  get 'events_subscribes/destroy/:event_id', :action => 'destroy', :controller => 'events_subscribes', :as => 'unsubscribe_event'
  get 'events_accept_members/create/:event_id', :action => 'create', :controller => 'accepted_event_members', :as => 'accept_member_event'
  get 'events_accept_members/destroy/:event_id', :action => 'destroy', :controller => 'accepted_event_members', :as => 'decline_member_event'

  get 'members_request/create/:community_id', :action => 'create', :controller => 'members_requests', :as => 'create_member_request'
  get 'members_request/destroy/:request_id', :action => 'destroy', :controller => 'members_requests', :as => 'destroy_member_request'
  get 'members_request/add/:request_id', :action => 'add', :controller => 'members_requests', :as => 'add_member_request'
  get 'members_request/index/:community_id', :action => 'index', :controller => 'members_requests', :as => 'index_member_request'

  get 'notifies/:community_id', to: 'notifies#new', :as => :notify_new
  post 'notifies/create/:community_id', to: 'notifies#create', :as => :notify_create

  post 'support/create/', to: 'support#create', :as => :support_create

  get 'my_events', to: 'events#my_events', :as => :my_events

  get 'search/users'
  get 'search/infogroups'
  get 'search/teams'
  get 'search/photos'
  get 'search/videos'
  get 'search/spots'
  get 'search/events'

  resources :adverts
  resources :users do
    member do
      get 'friends'
      get 'search_friend'
      get 'add_to_friends'
      get 'remove_from_friends'
      get 'messages'
      get 'communities'
      post 'invite_to_friend'
    end
    resources :photoalbums do
      resources :photos
      get 'upload'
    end
    resources :videoalbums do
      resources :videos
      get 'upload'
    end

  end
  resources :comments
  get 'search_event' => 'events#search_event'
  resources :events do
    resources :photoalbums do
      resources :photos
      get 'upload'
    end
    resources :videoalbums do
      resources :videos
      get 'upload'
    end
  end
  resources :messages
  resources :sport_events do
    resources :photoalbums do
      resources :photos
      get 'upload'
    end
    resources :videoalbums do
      resources :videos
      get 'upload'
    end
  end
  resources :ads do
    resources :photoalbums do
      resources :photos
      get 'upload'
    end
    resources :videoalbums do
      resources :videos
      get 'upload'
    end
  end

  get "search_comm" => "communities#search_comm"
  resources :communities do
    member do
      get 'members'
      get 'member/:user_id' , :action => 'member'
      put 'member/:user_id' , :action => 'edit_member'
      get 'membership_request'
      get 'invite'
      get 'membership_invite/:user_id' , :action => 'membership_invite'
      get 'membership_cancel'
    end

    resources :photoalbums do
      resources :photos
      get 'upload'
    end
    resources :videoalbums do
      resources :videos
      get 'upload'
    end
  end
  get '/communities/get_sports/:id' => 'communities#get_sports'

  resources :spots do
    resources :photoalbums do
      resources :photos
      get 'upload'
    end
    resources :videoalbums do
      resources :videos
      get 'upload'
    end
  end

  devise_for :users,
             :controllers => {
                 :passwords => 'users/passwords',
                 :registrations => 'users/registrations',
                 :sessions => 'users/sessions'
             },
             :path => '',
             :path_names => {
                 :sign_in => 'login', :sign_out => 'logout',
                 :password => 'password', :confirmation => 'confirmation',
                 :unlock => 'unlock',
                 :sign_up => 'registration'
             }

  match 'images/:id/:name' => 'images#download'

  match 'about' => 'static#about'
  match 'features' => 'static#features'
  match 'offerta' => 'static#offerta'
  match 'advert' => 'static#advert'
  devise_scope :user do
    root :to => 'devise/sessions#new'
  end

end

app/models/spot.rb
class Spot < ActiveRecord::Base
  attr_accessible :about, :kind, :name, :paid, :place_id, :size, :user_id, :address

  belongs_to :place
  belongs_to :user

  validates_presence_of :name

  has_many :comments, as: :commentable, order: 'date DESC', dependent: :destroy
  has_many :photoalbums, :as => :photoalbumable, order: 'created_at DESC'
  has_many :videoalbums, :as => :videoalbumable, order: 'created_at DESC'

  KINDS = { 'Открытая'=> 0, 'Крытая'=> 1 }
  PAIDS = { 'Бесплатная'=>0, 'Платная'=> 1 }


  has_many :favorites, as: :favoritable, dependent: :destroy

  def fullname
    self.name
  end


  include ActionView::Helpers

  def full_description
    truncate(self.about, length: 300)
  end



  def self.search(params)
    teams = self
    if params[:q].present?
      teams = teams.where('about LIKE ? OR name LIKE ?', "%#{params[:q]}%", "%#{params[:q]}%")
    end
    if params[:name].present?
      teams = teams.where('name LIKE ?', "%#{params[:name]}%")
    end
    if params[:place].present?
      place = Place.find(params[:place])
      places_ids = place.self_and_descendants.pluck(:id)
      teams = teams.where('place_id IN(?)', places_ids)
    end

    teams
  end

end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController

  before_filter :authenticate_user!

  # GET /spots
  # GET /spots.json
  def index


    @spots = Spot.all

    render layout: 'profile'
  end

  # GET /spots/1
  # GET /spots/1.json
  def show
    @spot = Spot.find(params[:id])
    @user = current_user
    render layout: 'profile'
  end


  # GET /spots/new
  # GET /spots/new.json
  def new
    @spot = Spot.new
    render layout: "profile"
  end

  # GET /spots/1/edit
  def edit
    @spot = Spot.find(params[:id])
    render layout: "profile"
  end



  # POST /spots
  # POST /spots.json
  def create
    @spot = Spot.new(spot_params)
    @spot.user_id = current_user.id

    if @spot.save
      flash.now[:notice] = 'Данные успешно сохранены'
      respond_to do |format|
        format.html { redirect_to spot_path(@spot)  }
      end
    else
      respond_to do |format|
        flash.now[:error] = 'Данные не сохранены. Проверьте введенные данные на наличие ошибок.'
        format.html { render action: 'new' }
      end
    end

  end


  # PUT /spots/1
  # PUT /spots/1.json
  def update
    @spot = Spot.find(params[:id])


    if @spot.update_attributes(spot_params)
      flash.now[:notice] = 'Данные успешно сохранены'
    else
      flash.now[:error] = 'Данные не сохранены. Проверьте введенные данные на наличие ошибок.'
    end

    respond_to do |format|
      format.html { render action: 'edit' }
      format.js { render action: 'edit' }
    end
  end

  # DELETE /spots/1
  # DELETE /spots/1.json
  def destroy
    @spot = Spot.find(params[:id])
    @spot.destroy

    respond_to do |format|
      format.html { redirect_to spots_url }
      format.json { head :no_content }
    end
  end

  private

  def spot_params
    allowed = [:name, :place_id, :kind, :paid, :about, :address ]

    params.require(:spot).permit( *allowed )
  end

end

app/views/spots/_form.html.slim
.FormBody
  = simple_nested_form_for @spot do |f|

    = f.input :name, input_html: {:class => 'input-block-level'}
    .clearBth
    = f.input :about, input_html: {:class => 'input-block-level'}
    .clearBth
    = f.input :address, input_html: {:class => 'input-block-level'}
    .clearBth
    = f.input :kind, collection: Spot::KINDS, as: :select, input_html: {:class => 'input-block-level'}
    .clearBth
    = f.input :paid, collection: Spot::PAIDS, as: :select, input_html: {:class => 'input-block-level'}
    .clearBth
    = f.input :place_id, as: :select, collection: Place.ordering, input_html: {:class => 'chosen-select', style: 'width: 100%', 'data-placeholder'=>'Выберите местонахождение'}, :include_blank => true

    button Сохранить изменения

app/views/spots/_list.html.slim
- spots.each do |obj|
  .grpBody
    .postText
      h1
        a href='#{spot_path obj}' = obj.name
      - unless obj.place.nil?
        span.geo = obj.place.fullname
        |  &nbsp;
      - unless obj.paid.empty?
        span.info = obj.paid == '0' ? 'Бесплатная' : 'Платная'
        |  &nbsp;
      - unless obj.kind.empty?
        span.info = obj.kind == '0' ? 'Открытая' : 'Крытая'
      .clearBth
      .grpText
        p = truncate obj.about, length: 300


      div style="float: right;"
        - if can? :update, obj
          = link_to '<i class="icon-pencil"></i> Редактировать'.html_safe, edit_spot_path(obj), class: 'btn btn-mini'
        - if can? :destroy, obj
          = link_to '<i class="icon-remove"></i> Удалить'.html_safe, obj, :confirm => 'Вы уверены?', :method => :delete, class: 'btn btn-mini'
      / div style='line-height: 22px;'
      /   a href='#{spot_path obj}'
      /     = obj.comments.count.to_s + ' ' + Russian::p(obj.comments.count,'отзыв','отзыва','отзывов')

app/views/spots/edit.html.slim
main
  section
    .grpFilter
      h1 Редактирование площадки
    .grpBody
      = render 'form'

app/views/spots/index.html.slim
main
  section
    .grpFilter
      h1 Площадки
      a.custom_btn.search_btn href='/search/spots/'
        button Найти площадку
      - if can? :create, Spot
        = link_to new_spot_path do
          button Добавить площадку
    = render partial: 'spots/list', locals: {:spots=>@spots}

app/views/spots/new.html.slim
main
  section
    .grpFilter
      h1 Создание площадки
    .grpBody
      = render 'form'

app/views/spots/show.html.slim
main
  section
    .grpFilter
      h1 = @spot.name
    .grpBody
      .btn-group style="float: right;"
        - if can? :update, @spot
          = link_to '<i class="icon-pencil"></i>'.html_safe, edit_spot_path(@spot), class: 'btn btn-mini'
        - if can? :destroy, @spot
          = link_to '<i class="icon-remove"></i>'.html_safe, @spot, :confirm => 'Вы уверены?', :method => :delete, class: 'btn btn-mini'
      div
        - unless @spot.place.nil?
          span.geo = @spot.place.fullname
        - unless @spot.paid.nil?
          span.info = @spot.paid == 0 ? 'Бесплатная' : 'Платная'
        - unless @spot.kind.nil?
          span.info = @spot.kind == 0 ? 'Открытая' : 'Крытая'
      div.clearBth
      / div.favorite id='favorite_#{@spot.class.to_s}_#{@spot.id.to_s}'
      /   = render partial: 'favorites/favorite', locals: { model: @spot }

      .row
        .span4
          h5
            a href='/spots/#{@spot.id.to_s}/photoalbums/' Фотографии
          - if @spot.photoalbums.any?
            - i = 5
            - @spot.photoalbums.each do |photoalbum|
              - if i > 0
                - photoalbum.photos.limit(i).each do |photo|
                  div.img_spots
                    a href="/spots/#{@spot.id}/photoalbums/#{photo.photoalbum_id}/photos/#{photo.id}" class='modal_link'
                      img src="#{photo.photo.thumb.url}"
                  - i=i-1
          - else
            p.muted Фотографий пока нет

        .span4
          h5
            a href='/spots/#{@spot.id.to_s}/videoalbums/'
              ' Видео
          - if @spot.videoalbums.any?
            - i = 2
            - @spot.videoalbums.each do |videoalbum|
              - if i > 0
                - videoalbum.videos.limit(i).each do |video|
                  div style='width: 49%; margin: 0 1% 10px 0; float: left;'
                    a href="/spots/#{@spot.id}/videoalbums/#{video.videoalbum_id}/videos/#{video.id}" class='modal_link'
                      img class="img-rounded" src="#{video.thumb}"
                  - i=i-1

          - if !@spot.videoalbums.any? || i==2
            p.muted Видео пока нет
      .clearBth
      div
        p = @spot.address

        p = @spot.about.html_safe
      .clearBth

    = render partial: 'comments/form2', locals: { model: @spot, reverse: true, limit: 30}
    .clearBth
    div style='width: 100%'
      div id="map" style='width: 100%; height: 400px;'

    /
      script src="//maps.google.com/maps/api/js?v=3.13&sensor=false&libraries=geometry" type="text/javascript"
      script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'
      script type='text/javascript'
        |
          $(document).ready(function(){
          mmap = Gmaps.build('Google');
          mmap.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
            markers = handler.addMarkers([
              {
                "lat": 50,
                "lng": 50,
                "icon": '1'
              }
            ]);
            mmap.bounds.extendWith(markers);
            mmap.fitMapToBounds();
          });
          });