config/routes.rb
Playtogether::Application.routes.draw do

  resources :key_values

  namespace :admin do
    resources :users do
      member do
        get 'user_ban'
      end
    end

    resources :photoalbums do
      resources :photos
      get 'upload'
    end

    resources :photos do
      get 'upload'
    end

    resources :posting_updates do
    end

    resources :places do
      member do
        get 'spots_for_select'
        get 'children_nodes'
      end
    end

    resources :sport_types do
      member do
        get 'children_nodes'
      end
    end
  end

  get 'likes/like'
  get 'likes/unlike'
  get 'likes/plus_minus'
  get 'retweets/create'

  match  'favorites' => 'favorites#index'
  get 'favorites/favorite'
  get 'favorites/unfavorite'

  match  'invites' => 'Invites#index'
  get 'invites/accept/:invite_id', :action => 'accept', :controller => 'invites', :as => 'accept_invite'
  get 'invites/cancel/:invite_id', :action => 'cancel', :controller => 'invites', :as => 'cancel_invite'

  get 'events_subscribes/create/:event_id', :action => 'create', :controller => 'events_subscribes', :as => 'subscribe_event'
  get 'events_subscribes/destroy/:event_id', :action => 'destroy', :controller => 'events_subscribes', :as => 'unsubscribe_event'
  get 'events_accept_members/create/:event_id', :action => 'create', :controller => 'accepted_event_members', :as => 'accept_member_event'
  get 'events_accept_members/destroy/:event_id', :action => 'destroy', :controller => 'accepted_event_members', :as => 'decline_member_event'

  get 'members_request/create/:community_id', :action => 'create', :controller => 'members_requests', :as => 'create_member_request'
  get 'members_request/destroy/:request_id', :action => 'destroy', :controller => 'members_requests', :as => 'destroy_member_request'
  get 'members_request/add/:request_id', :action => 'add', :controller => 'members_requests', :as => 'add_member_request'
  get 'members_request/index/:community_id', :action => 'index', :controller => 'members_requests', :as => 'index_member_request'

  get 'notifies/:community_id', to: 'notifies#new', :as => :notify_new
  post 'notifies/create/:community_id', to: 'notifies#create', :as => :notify_create

  post 'support/create/', to: 'support#create', :as => :support_create

  get 'my_events', to: 'events#my_events', :as => :my_events

  get 'search/users'
  get 'search/infogroups'
  get 'search/teams'
  get 'search/photos'
  get 'search/videos'
  get 'search/spots'
  get 'search/events'

  resources :adverts
  resources :users do
    member do
      get 'friends'
      get 'search_friend'
      get 'add_to_friends'
      get 'remove_from_friends'
      get 'messages'
      get 'communities'
      post 'invite_to_friend'
    end
    resources :photoalbums do
      resources :photos
      get 'upload'
    end
    resources :videoalbums do
      resources :videos
      get 'upload'
    end

  end
  resources :comments
  get 'search_event' => 'events#search_event'
  resources :events do
    resources :photoalbums do
      resources :photos
      get 'upload'
    end
    resources :videoalbums do
      resources :videos
      get 'upload'
    end
  end
  resources :messages
  resources :sport_events do
    resources :photoalbums do
      resources :photos
      get 'upload'
    end
    resources :videoalbums do
      resources :videos
      get 'upload'
    end
  end
  resources :ads do
    resources :photoalbums do
      resources :photos
      get 'upload'
    end
    resources :videoalbums do
      resources :videos
      get 'upload'
    end
  end

  get "search_comm" => "communities#search_comm"
  resources :communities do
    member do
      get 'members'
      get 'member/:user_id' , :action => 'member'
      put 'member/:user_id' , :action => 'edit_member'
      get 'membership_request'
      get 'invite'
      get 'membership_invite/:user_id' , :action => 'membership_invite'
      get 'membership_cancel'
    end

    resources :photoalbums do
      resources :photos
      get 'upload'
    end
    resources :videoalbums do
      resources :videos
      get 'upload'
    end
  end
  get '/communities/get_sports/:id' => 'communities#get_sports'

  resources :spots do
    resources :photoalbums do
      resources :photos
      get 'upload'
    end
    resources :videoalbums do
      resources :videos
      get 'upload'
    end
  end

  devise_for :users,
             :controllers => {
                 :passwords => 'users/passwords',
                 :registrations => 'users/registrations',
                 :sessions => 'users/sessions'
             },
             :path => '',
             :path_names => {
                 :sign_in => 'login', :sign_out => 'logout',
                 :password => 'password', :confirmation => 'confirmation',
                 :unlock => 'unlock',
                 :sign_up => 'registration'
             }

  match 'images/:id/:name' => 'images#download'

  match 'about' => 'static#about'
  match 'features' => 'static#features'
  match 'offerta' => 'static#offerta'
  match 'advert' => 'static#advert'
  devise_scope :user do
    root :to => 'devise/sessions#new'
  end

end

app/models/photoalbum.rb
class Photoalbum < ActiveRecord::Base
  attr_accessible :community_id, :name, :user_id
  has_many :photos, order: 'id DESC'
  belongs_to :photoalbumable, polymorphic: true

end

app/controllers/admin/photoalbums_controller.rb
class Admin::PhotoalbumsController < ApplicationController

  before_filter :authenticate_user!

  # GET /photoalbums
  # GET /photoalbums.json
  def index
    @photos_sys = Photoalbum.find_by_photoalbumable_type("System").photos
    @photos_sli = Photoalbum.find_by_photoalbumable_type("Slider").photos
    @photoalbum_sys = Photoalbum.find_by_photoalbumable_type("System")
    @photoalbum_sli = Photoalbum.find_by_photoalbumable_type("Slider")
    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /photoalbums/1
  # GET /photoalbums/1.json
  def show
    @photoalbum = Photoalbum.find_by_photoalbumable_type("System")

    respond_to do |format|
      format.html
    end
  end

  def upload
    @photoalbum = Photoalbum.find(params[:photoalbum_id])

    respond_to do |format|
      format.html
    end
  end


  # GET /photoalbums/new
  # GET /photoalbums/new.json
  def new
    @photoalbum = Photoalbum.new

    respond_to do |format|
      format.html
    end
  end


  def update

    @photoalbum = Photoalbum.find(params[:id])
    photoalbumable = @photoalbum.photoalbumable
    @photoalbum.name = params[:photoalbum][:name]
    @photoalbum.save


    redirect_to photoalbumable

  end


  # DELETE /photoalbums/1
  # DELETE /photoalbums/1.json
  def destroy
    @photoalbum = Photoalbum.find(params[:id])
    photoalbumable = @photoalbum.photoalbumable
    @photoalbum.destroy
    redirect_to photoalbumable

  end

  private

  def photoalbum_params
    allowed = [:name]

    params.require(:photoalbum).permit(*allowed)
  end

end

app/controllers/photoalbums_controller.rb
class PhotoalbumsController < ApplicationController

  before_filter :authenticate_user!

  # GET /photoalbums
  # GET /photoalbums.json
  def index
    if !params[:user_id].blank?

      @user = User.find(params[:user_id])

      @photoalbums = @user.photoalbums.accessible_by(current_ability).order("created_at DESC")

    elsif !params[:community_id].blank?

        @community = Community.find(params[:community_id])
        @photoalbums = @community.photoalbums.accessible_by(current_ability).order("created_at DESC")
    elsif !params[:event_id].blank?

      @event = Event.find(params[:event_id])
      @photoalbums = @event.photoalbums.order("created_at DESC")
    elsif !params[:spot_id].blank?

      @spot = Spot.find(params[:spot_id])
      @photoalbums = @spot.photoalbums.order("created_at DESC")
    elsif !params[:sport_event_id].blank?

      @sport_event = SportEvent.find(params[:sport_event_id])
      @photoalbums = @sport_event.photoalbums.order("created_at DESC")
    elsif !params[:ad_id].blank?

      @ad = Ad.find(params[:ad_id])
      @photoalbums = @ad.photoalbums.order("created_at DESC")
    end

    render layout: 'profile'
  end

  # GET /photoalbums/1
  # GET /photoalbums/1.json
  def show
    @photoalbum = Photoalbum.find(params[:id])

    unless params[:user_id].blank?

      @user = User.find(params[:user_id])
    end

    unless params[:community_id].blank?

         @community = Community.find(params[:community_id])
    end

    unless params[:event_id].blank?

      @event = Event.find(params[:event_id])
    end
    unless params[:spot_id].blank?

        @spot = Spot.find(params[:spot_id])
    end
    unless params[:sport_event_id].blank?

      @sport_event = SportEvent.find(params[:sport_event_id])
    end
    unless params[:ad_id].blank?

      @ad = Ad.find(params[:ad_id])
    end

    render layout: "profile"
  end

  def upload
    @photoalbum = Photoalbum.find(params[:photoalbum_id])

    unless params[:user_id].blank?

      @user = User.find(params[:user_id])
    end
    unless params[:community_id].blank?

      @community = Community.find(params[:community_id])
    end
    unless params[:event_id].blank?

      @spot = Spot.find(params[:spot_id])
    end
    unless params[:spot_id].blank?

      @spot = Spot.find(params[:spot_id])
    end
    unless params[:sport_event_id].blank?

      @sport_event = SportEvent.find(params[:sport_event_id])

    end
    unless params[:ad_id].blank?

      @ad = Ad.find(params[:ad_id])
    end

    respond_to do |format|
      format.html { render layout: "profile" }
      format.json { render json: {files: [@photoalbum.to_jq_upload]}, status: :created, location: @photoalbum }
    end
  end


  # GET /photoalbums/new
  # GET /photoalbums/new.json
  def new
    @photoalbum = Photoalbum.new

    if !params[:user_id].blank?

      @user = User.find(params[:user_id])
    elsif !params[:community_id].blank?
        @community = Community.find(params[:community_id])
    elsif !params[:event_id].blank?
      @event = Event.find(params[:event_id])
    elsif !params[:spot_id].blank?
      @spot = Spot.find(params[:spot_id])
    elsif !params[:sport_event_id].blank?
      @sport_event = SportEvent.find(params[:sport_event_id])
    elsif !params[:ad_id].blank?
      @ad = Ad.find(params[:ad_id])
    end

    render layout: "profile"
  end

  # GET /photoalbums/1/edit
  def edit

    if !params[:user_id].blank?

      @user = User.find(params[:user_id])
    elsif !params[:community_id].blank?

      @community = Community.find(params[:community_id])
    elsif !params[:event_id].blank?

      @event = Event.find(params[:event_id])
    elsif !params[:spot_id].blank?

      @spot = Spot.find(params[:spot_id])
    elsif !params[:sport_event_id].blank?

      @sport_event = SportEvent.find(params[:sport_event_id])
    elsif !params[:ad_id].blank?
      @ad = Ad.find(params[:ad_id])

    end

    @photoalbum = Photoalbum.find(params[:id])
    render layout: 'profile'
  end


  # POST /photoalbums
  # POST /photoalbums.json
  def create

    @photoalbum = Photoalbum.new(photoalbum_params)

    if !params[:user_id].blank?

      @user = User.find(params[:user_id])
      @photoalbum.photoalbumable = @user

      @photoalbum.save

      redirect_to '/users/'+@photoalbum.photoalbumable_id.to_s+'/photoalbums'

    elsif !params[:community_id].blank?

      @community = Community.find(params[:community_id])
      @photoalbum.photoalbumable = @community

      @photoalbum.save

      redirect_to '/communities/'+@photoalbum.photoalbumable_id.to_s+'/photoalbums'

    elsif !params[:event_id].blank?

      @event = Event.find(params[:event_id])
      @photoalbum.photoalbumable = @event

      @photoalbum.save

      redirect_to '/events/'+@photoalbum.photoalbumable_id.to_s+'/photoalbums'
    elsif !params[:spot_id].blank?

      @spot = Spot.find(params[:spot_id])
      @photoalbum.photoalbumable = @spot

      @photoalbum.save

      redirect_to '/spots/'+@photoalbum.photoalbumable_id.to_s+'/photoalbums'
    elsif !params[:sport_event_id].blank?

      @sport_event = SportEvent.find(params[:sport_event_id])
      @photoalbum.photoalbumable = @sport_event

      @photoalbum.save

      redirect_to '/sport_events/'+@photoalbum.photoalbumable_id.to_s+'/photoalbums'
    elsif !params[:ad_id].blank?

      @ad = Ad.find(params[:ad_id])
      @photoalbum.photoalbumable = @ad

      @photoalbum.save

      redirect_to '/ads/'+@photoalbum.photoalbumable_id.to_s+'/photoalbums'

    end


  end

  def update


    @photoalbum = Photoalbum.find(params[:id])
    photoalbumable = @photoalbum.photoalbumable
    @photoalbum.name = params[:photoalbum][:name]
    @photoalbum.save


    redirect_to photoalbumable

  end


  # DELETE /photoalbums/1
  # DELETE /photoalbums/1.json
  def destroy
    @photoalbum = Photoalbum.find(params[:id])
    photoalbumable = @photoalbum.photoalbumable
    @photoalbum.destroy
    redirect_to photoalbumable

  end

  private

  def photoalbum_params
    allowed = [:name]

    params.require(:photoalbum).permit(*allowed)
  end

end

app/views/admin/photoalbums/_form.html.slim
- if @user || @community || @event || @spot || @sport_event || @ad
  - entity = @community if @community
  - entity = @user if @user
  - entity = @event if @event
  - entity = @spot if @spot
  - entity = @sport_event if @sport_event
  - entity = @ad if @ad
  = simple_nested_form_for [entity, @photoalbum] do |f|

    = f.input :name, input_html: {:class => 'input-block-level'}

    = f.submit 'Сохранить изменения', :class => 'btn btn-primary', style: 'margin-top: 3px'

app/views/admin/photoalbums/_upload.html.erb
  <p><strong>Загрузить фотографии:</strong></p>
  <%= form_for ["admin", @photoalbum, Photo.new], :html => { :multipart => true, :id => "fileupload"  } do |f| %>
    <!-- The fileupload-buttonbar contains buttons to add/delete files and start/cancel the upload -->
    <div class="row fileupload-buttonbar">
      <div class="span8">
        <!-- The fileinput-button span is used to style the file input field as button -->
        <span class="btn btn-success fileinput-button">
          <i class="icon-plus icon-white"></i>
          <span>Добавить фотографии</span>
          <%= f.file_field :photo, multiple: true %>
        </span>
        <button type="submit" class="btn btn-primary start">
          <i class="icon-upload icon-white"></i>
          <span>Загрузить все</span>
        </button>
        <button type="reset" class="btn btn-warning cancel">
          <i class="icon-ban-circle icon-white"></i>
          <span>Отменить загрузку</span>
        </button>
        <% obj_name = @photoalbum.photoalbumable.class.to_s.underscore %>
        <% obj_name = 'community' if obj_name == 'team' %>
      </div>
    </div>
    <!-- The loading indicator is shown during image processing -->
    <div class="fileupload-loading"></div>
    <br>
    <!-- The table listing the files available for upload/download -->

      <table class="files table table-bordered table-striped">

      </table>

  <% end %>


<script>
  var fileUploadErrors = {
  maxFileSize: 'File is too big',
  minFileSize: 'File is too small',
  acceptFileTypes: 'Filetype not allowed',
  maxNumberOfFiles: 'Max number of files exceeded',
  uploadedBytes: 'Uploaded bytes exceed file size',
  emptyResult: 'Empty file upload result'
  };
</script>

<!-- The template to display files available for upload -->
<script id="template-upload" type="text/x-tmpl">

  {% for (var i=0, file; file=o.files[i]; i++) { %}
  <tr class="template-upload fade">
    <td class="preview"><span class="fade"></span></td>
    <td class="name"><span>{%=file.name%}</span></td>
    <td class="size"><span>{%=o.formatFileSize(file.size)%}</span></td>
    {% if (file.error) { %}
    <td class="error" colspan="2"><span class="label label-important">{%=locale.fileupload.error%}</span> {%=locale.fileupload.errors[file.error] || file.error%}</td>
    {% } else if (o.files.valid && !i) { %}
    <td>
      <div class="progress progress-success progress-striped active"><div class="bar" style="width:0%;"></div></div>
    </td>
    <td class="start">{% if (!o.options.autoUpload) { %}
      <button class="btn btn-mini btn-primary">
        <i class="icon-upload icon-white"></i>
        <span>Загрузить</span>
      </button>
      {% } %}</td>
    {% } else { %}
    <td colspan="2"></td>
    {% } %}
    <td class="cancel">{% if (!i) { %}
      <button class="btn btn-mini btn-danger">
        <i class="icon-ban-circle icon-white"></i>
        <span>Удалить</span>
      </button>
      {% } %}</td>
  </tr>
  {% } %}
</script>
<!-- The template to display files available for download -->
<script id="template-download" type="text/x-tmpl">

</script>

<script type="text/javascript" charset="utf-8">
  $(function () {
      // Initialize the jQuery File Upload widget:
      $('#fileupload').fileupload();
      //
      // Load existing files:
      $.getJSON($('#fileupload').prop('action'), function (files) {
        var fu = $('#fileupload').data('blueimpFileupload'),
          template;
        fu._adjustMaxNumberOfFiles(-files.length);
        console.log(files);
        template = fu._renderDownload(files)
          .appendTo($('#fileupload .files'));
        // Force reflow:
        fu._reflow = fu._transition && template.length &&
          template[0].offsetWidth;
        template.addClass('in');
        $('#loading').remove();
      });

  });
</script>

app/views/admin/photoalbums/edit.html.slim
h1 Редактирование фотоальбома

div id="form_container"
  = render 'form'

app/views/admin/photoalbums/index.html.slim
h1
  ' Фон

div style="margin: 0 0 20px;"
  - obj_name = @photoalbum_sys.photoalbumable.class.to_s.underscore


.row
  - @photos_sys.each do |photo|
    .span2 style='margin-bottom: 15px;'
      =image_tag photo.photo
      p style='font-size: 11px; line-height: 1.33;  margin-left: 5px; margin-right: 5px;'
        = link_to 'Удалить'.html_safe, "#{admin_photos_path}/#{photo.id}", :confirm => 'Вы уверены?', :method => :delete

div style="margin: 0 0 20px;"
  - obj_name = @photoalbum_sys.photoalbumable.class.to_s.underscore
  - obj_name = 'community' if obj_name == 'team'
  =link_to "photoalbums/#{@photoalbum_sys.id}/upload"
    | Загрузить фото

h1
  ' Альбом для слайдеров

div style="margin: 0 0 20px;"
  - obj_name = @photoalbum_sli.photoalbumable.class.to_s.underscore


.row
  - @photos_sli.each do |photo|
    .span2 style='margin-bottom: 15px;'
      =image_tag photo.photo
      p style='font-size: 11px; line-height: 1.33;  margin-left: 5px; margin-right: 5px;'
        = link_to 'Удалить'.html_safe, "#{admin_photos_path}/#{photo.id}", :confirm => 'Вы уверены?', :method => :delete

div style="margin: 0 0 20px;"
  - obj_name = @photoalbum_sli.photoalbumable.class.to_s.underscore
  - obj_name = 'community' if obj_name == 'team'
  =link_to "photoalbums/#{@photoalbum_sli.id}/upload"
    | Загрузить фото

app/views/admin/photoalbums/new.html.slim
h1 Создание фотоальбома

div id='form_container'
  == render 'form'

app/views/admin/photoalbums/show.html.slim
h1
  ' Фотоальбом
  = @photoalbum.name

div style="margin: 0 0 20px;"
  - obj_name = @photoalbum.photoalbumable.class.to_s.underscore
  - obj_name = 'community' if obj_name == 'team'
  =link_to "#{@photoalbum.id}/upload"
    | Загрузить фото


.row

app/views/admin/photoalbums/upload.html.slim
- if @user
  - breadcrumb :user_photoalbum, @photoalbum, @user
- if @community
  - breadcrumb :community_photoalbum, @photoalbum, @community
- if @ad
  - breadcrumb :ad_photoalbum, @photoalbum, @ad

h1
  ' Фотоальбом
  = @photoalbum.name

= render 'upload'

=link_to 'Вернуться к системным альбомам'